builds:
-
  env:
    - CGO_ENABLED=0
  goos:
    - windows
    - darwin
    - linux
  binary: packr

archive:
  replacements:
    darwin: macOS
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
